import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCKERFILE = (ROOT.parent / "Dockerfile").read_text(encoding="utf-8")
SERVER = (ROOT / "server.py").read_text(encoding="utf-8")
APP = (ROOT / "static" / "app.js").read_text(encoding="utf-8")
INDEX = (ROOT / "static" / "index.html").read_text(encoding="utf-8")
TOKENS = (ROOT / "static" / "theme" / "tokens.css").read_text(encoding="utf-8")
FOUNDATIONS = (ROOT / "static" / "theme" / "foundations.css").read_text(encoding="utf-8")
RESPONSIVE = (ROOT / "static" / "theme" / "responsive.css").read_text(encoding="utf-8")
COMPONENTS = (ROOT / "static" / "theme" / "components.css").read_text(encoding="utf-8")
CONTROL_CENTER_CSS = (ROOT / "static" / "theme" / "control-center.css").read_text(encoding="utf-8")
MOTION = (ROOT / "static" / "theme" / "motion.css").read_text(encoding="utf-8")
PRODUCTIVITY = (ROOT / "static" / "theme" / "productivity.css").read_text(encoding="utf-8")
EXPERIENCE = (ROOT / "static" / "js" / "ui" / "experience.js").read_text(encoding="utf-8")
MOTION_JS = (ROOT / "static" / "js" / "ui" / "motion.js").read_text(encoding="utf-8")
DIALOGS_JS = (ROOT / "static" / "js" / "ui" / "dialogs.js").read_text(encoding="utf-8")
TENDER_VIEWER_JS = (ROOT / "static" / "js" / "ui" / "tender-viewer.js").read_text(encoding="utf-8")
NAVIGATION_JS = (ROOT / "static" / "js" / "ui" / "navigation.js").read_text(encoding="utf-8")
STATE_JS = (ROOT / "static" / "js" / "core" / "state.js").read_text(encoding="utf-8")
FORMATTERS_JS = (ROOT / "static" / "js" / "core" / "formatters.js").read_text(encoding="utf-8")
HTTP_JS = (ROOT / "static" / "js" / "core" / "http.js").read_text(encoding="utf-8")
PREFERENCES_JS = (ROOT / "static" / "js" / "core" / "preferences.js").read_text(encoding="utf-8")
DRAFTS_JS = (ROOT / "static" / "js" / "core" / "drafts.js").read_text(encoding="utf-8")
COMMAND_JS = (ROOT / "static" / "js" / "ui" / "command-palette.js").read_text(encoding="utf-8")
WORKSPACE_TABS_JS = (ROOT / "static" / "js" / "ui" / "workspace-tabs.js").read_text(encoding="utf-8")
RECORD_DISCLOSURE_JS = (ROOT / "static" / "js" / "ui" / "record-disclosure.js").read_text(encoding="utf-8")
INSTALL_APP_JS = (ROOT / "static" / "js" / "ui" / "install-app.js").read_text(encoding="utf-8")
SYSTEM_DATE_JS = (ROOT / "static" / "js" / "ui" / "system-date.js").read_text(encoding="utf-8")
CONTROL_CENTER_JS = (ROOT / "static" / "js" / "modules" / "control-center.js").read_text(encoding="utf-8")
INVENTORY_JS = (ROOT / "static" / "js" / "modules" / "inventory.js").read_text(encoding="utf-8")
INVENTORY_CSS = (ROOT / "static" / "theme" / "inventory.css").read_text(encoding="utf-8")
WORKFLOW_ITEMS_JS = (ROOT / "static" / "js" / "modules" / "workflow-items.js").read_text(encoding="utf-8")
WORKFLOW_ITEMS_CSS = (ROOT / "static" / "theme" / "workflow-items.css").read_text(encoding="utf-8")
PERMISSIONS_CSS = (ROOT / "static" / "theme" / "permissions.css").read_text(encoding="utf-8")
MANAGEMENT_JS = (ROOT / "static" / "js" / "modules" / "management-control.js").read_text(encoding="utf-8")
MANAGEMENT_CSS = (ROOT / "static" / "theme" / "management-control.css").read_text(encoding="utf-8")
FISCAL_INTEGRATION_JS = (ROOT / "static" / "js" / "modules" / "fiscal-integration.js").read_text(encoding="utf-8")
FISCAL_INTEGRATION_CSS = (ROOT / "static" / "theme" / "fiscal-integration.css").read_text(encoding="utf-8")
TENDER_KEYWORDS_JS = (ROOT / "static" / "js" / "modules" / "tender-keywords.js").read_text(encoding="utf-8")
TENDERS_CSS = (ROOT / "static" / "theme" / "tenders.css").read_text(encoding="utf-8")
TENDER_DOCUMENTS_JS = (ROOT / "static" / "js" / "modules" / "tender-documents.js").read_text(encoding="utf-8")
TENDER_DOCUMENTS_CSS = (ROOT / "static" / "theme" / "tender-documents.css").read_text(encoding="utf-8")
TENDER_PROPOSAL_JS = (ROOT / "static" / "js" / "modules" / "tender-proposal.js").read_text(encoding="utf-8")
TENDER_PROPOSAL_CSS = (ROOT / "static" / "theme" / "tender-proposal.css").read_text(encoding="utf-8")
TENDER_PORTAL_AGENT_JS = (ROOT / "static" / "js" / "modules" / "tender-portal-agent.js").read_text(encoding="utf-8")
TENDER_PORTAL_AGENT_CSS = (ROOT / "static" / "theme" / "tender-portal-agent.css").read_text(encoding="utf-8")
TENDER_CONTROL_JS = (ROOT / "static" / "js" / "modules" / "tender-control.js").read_text(encoding="utf-8")
TENDER_CONTROL_CSS = (ROOT / "static" / "theme" / "tender-control.css").read_text(encoding="utf-8")
TENDER_AGENT_WORKER = (ROOT.parent / "tools" / "tender_portal_worker.py").read_text(encoding="utf-8")
TENDER_AGENT_COMPOSE = (ROOT.parent / "tools" / "tender-agent" / "compose.yaml").read_text(encoding="utf-8")
SERVICE_WORKER = (ROOT / "static" / "service-worker.js").read_text(encoding="utf-8")
MANIFEST = (ROOT / "static" / "manifest.json").read_text(encoding="utf-8")


class FrontendContractTests(unittest.TestCase):
    def test_public_labels_use_plain_system_language(self):
        self.assertIn("MÓDULOS</p>", APP)
        self.assertNotIn("MÓDULOS SIVS", APP)
        for label in (
            "Pergunte ao SIVS",
            "Buscar em todo o SIVS",
            "explicar como usar o SIVS",
        ):
            self.assertNotIn(label, INDEX)
        self.assertIn("Pergunte ao sistema", INDEX)
        self.assertIn("Buscar em todo o sistema", INDEX)
        self.assertIn("A IA observa e sugere; o sistema valida piso", TENDER_PORTAL_AGENT_JS)

    def test_workspace_tabs_follow_navigation_permissions_and_accessibility(self):
        self.assertIn('id="workspaceTabs"', INDEX)
        self.assertIn('aria-label="Abas de trabalho abertas"', INDEX)
        self.assertIn('/js/ui/workspace-tabs.js?v=2.2.0-workspace-tabs-59', INDEX)
        self.assertIn('/js/ui/workspace-tabs.js?v=2.2.0-workspace-tabs-59', SERVICE_WORKER)
        self.assertIn('canAccess(screen)', WORKSPACE_TABS_JS)
        self.assertIn('aria-current="page"', WORKSPACE_TABS_JS)
        self.assertIn('data-workspace-tab-close', WORKSPACE_TABS_JS)
        self.assertIn('ArrowLeft', WORKSPACE_TABS_JS)
        self.assertIn('ArrowRight', WORKSPACE_TABS_JS)
        self.assertIn('openTabs()', PREFERENCES_JS)
        self.assertIn('closeTab(screen)', PREFERENCES_JS)
        self.assertIn('ui.workspaceTabs?.activate(screen)', APP)
        self.assertIn('button.setAttribute("aria-current", "page")', APP)
        self.assertIn('.workspace-tabs', PRODUCTIVITY)
        self.assertIn('.workspace-tab-close', PRODUCTIVITY)
        self.assertIn('@media (max-width: 760px)', PRODUCTIVITY)
        self.assertIn('sivs-v2.2.0-portal-agent-viewer-80', SERVICE_WORKER)

    def test_tender_keywords_use_accessible_chips_spreadsheets_and_measured_quality(self):
        for element_id in (
            "tenderKeywordEditor", "tenderKeywordChips", "tenderKeywordInput",
            "tenderKeywords", "importTenderKeywords", "downloadTenderKeywordTemplate",
            "tenderKeywordFile", "tenderKeywordReport", "tenderKeywordToggle",
            "tenderKeywordSummary",
        ):
            self.assertIn(f'id="{element_id}"', APP)
        self.assertIn('event.key === "Enter"', TENDER_KEYWORDS_JS)
        self.assertIn('event.key === ","', TENDER_KEYWORDS_JS)
        self.assertIn('/api/tenders/keywords/import', TENDER_KEYWORDS_JS)
        self.assertIn('aria-label', TENDER_KEYWORDS_JS)
        self.assertIn('setCollapsed(window.matchMedia("(max-width: 760px)").matches)', TENDER_KEYWORDS_JS)
        self.assertIn('.keyword-editor.is-collapsed', TENDERS_CSS)
        self.assertIn('data-tender-feedback', APP)
        self.assertIn('aria-label="Marcar edital como aderente"', APP)
        self.assertIn('aria-label="Marcar edital como não aderente"', APP)
        self.assertNotIn("👍", APP)
        self.assertNotIn("👎", APP)
        self.assertIn('id="tenderViewerStatus"', INDEX)
        self.assertIn('credentials: "same-origin"', TENDER_VIEWER_JS)
        self.assertIn('URL.createObjectURL(blob)', TENDER_VIEWER_JS)
        self.assertIn('X-SIVS-Previewable', TENDER_VIEWER_JS)
        self.assertIn('analysis?.status === "failed"', APP)
        self.assertIn('Precisão validada', APP)
        self.assertIn('var(--color-seccol)', TENDERS_CSS)
        self.assertIn('border-radius: var(--radius-pill)', TENDERS_CSS)
        self.assertIn('@media (max-width: 760px)', TENDERS_CSS)
        self.assertIn('/theme/tenders.css?v=2.2.0-tender-extraction-58', INDEX)
        self.assertIn('/js/modules/tender-keywords.js?v=2.2.0-ux-guidance-47', INDEX)
        self.assertIn('/js/modules/tender-keywords.js?v=2.2.0-ux-guidance-47', SERVICE_WORKER)

    def test_inventory_uses_dedicated_ledger_reservations_and_accessible_forms(self):
        self.assertIn('if (screen === "estoque") return await loadInventory()', APP)
        self.assertIn('/api/inventory/movements', INVENTORY_JS)
        self.assertIn('/api/inventory/reservations', INVENTORY_JS)
        self.assertIn('Disponível = físico − reservado', INVENTORY_JS)
        self.assertIn('LEDGER IMUTÁVEL', INVENTORY_JS)
        self.assertIn('aria-labelledby="inventoryMovementTitle"', INVENTORY_JS)
        self.assertIn('min="0.000001"', INVENTORY_JS)
        self.assertIn('data-release-reservation', INVENTORY_JS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', INVENTORY_CSS)
        self.assertIn('@media (max-width: 760px)', INVENTORY_CSS)
        self.assertIn('/theme/inventory.css?v=2.2.0-functional-control-43', INDEX)
        self.assertIn('/js/modules/inventory.js?v=2.2.0-functional-control-43', INDEX)
        self.assertIn('/js/modules/inventory.js?v=2.2.0-functional-control-43', SERVICE_WORKER)
        self.assertIn("CENTRAL FISCAL", APP)
        self.assertNotIn("fiscal_provider", APP)
        self.assertNotIn("Aguardando conector", APP)
        for vendor in ("bling", "tiny", "omie"):
            self.assertNotIn(vendor, (APP + INVENTORY_JS + INDEX).lower())

    def test_financial_forms_use_registered_partners_categories_and_progressive_disclosure(self):
        self.assertIn('["FISCAL", [["fiscal", "Central fiscal"], ["importacoes_xml", "Importar XML NF-e"]]]', APP)
        self.assertIn('setHeader("FISCAL", "Importar XML NF-e")', APP)
        self.assertIn('/api/financial/categories', APP)
        self.assertIn('F("categoria", "Categoria", "financial-category")', APP)
        self.assertIn('field.type === "financial-category"', APP)
        self.assertIn('partyRole: "F", relation: "Fornecedor", fieldLabel: "Fornecedor / favorecido"', APP)
        self.assertIn('partyRole: "C", relation: "Cliente", fieldLabel: "Cliente / pagador"', APP)
        self.assertNotIn('form.tipo_parte.value', APP)
        self.assertIn('if (pending === 0)', RECORD_DISCLOSURE_JS)
        self.assertIn('apply(true)', RECORD_DISCLOSURE_JS)

    def test_document_items_integrate_commercial_purchase_service_and_stock_flows(self):
        for element_id in (
            "recordDocumentItems", "documentItemsList", "addDocumentItem",
            "documentItemDialog", "documentItemForm", "documentInventoryActions",
        ):
            self.assertIn(f'id="{element_id}"', INDEX)
        self.assertIn('/api/records/${context.record.id}/items', WORKFLOW_ITEMS_JS)
        self.assertIn('/api/records/${context.record.id}/${action}', WORKFLOW_ITEMS_JS)
        self.assertIn('data-document-stock="fulfill-items"', WORKFLOW_ITEMS_JS)
        self.assertIn('data-document-stock="receive-items"', WORKFLOW_ITEMS_JS)
        self.assertIn('Baixando as peças no ledger em uma transação única', WORKFLOW_ITEMS_JS)
        self.assertIn('Registrando o recebimento no ledger em uma transação única', WORKFLOW_ITEMS_JS)
        self.assertIn('item.reservationStatus === "FULFILLED"', WORKFLOW_ITEMS_JS)
        self.assertIn('"propostas", "vendas", "solicitacoes_compra", "pedidos_compra", "ordens_servico"', WORKFLOW_ITEMS_JS)
        self.assertIn('min="0.000001"', INDEX)
        self.assertIn('Total calculado automaticamente pelos itens', WORKFLOW_ITEMS_JS)
        self.assertIn('@media (max-width: 620px)', WORKFLOW_ITEMS_CSS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', WORKFLOW_ITEMS_CSS)
        self.assertIn('/theme/workflow-items.css?v=2.2.0-erp-workflows-40', INDEX)
        self.assertIn('/js/modules/workflow-items.js?v=2.2.0-erp-workflows-40', INDEX)
        self.assertIn('/js/modules/workflow-items.js?v=2.2.0-erp-workflows-40', SERVICE_WORKER)

    def test_fiscal_readiness_sefaz_a1_and_accounting_export_are_integrated_safely(self):
        self.assertIn('/api/fiscal/readiness', APP)
        self.assertIn('SIVSFiscalIntegration.render', APP)
        self.assertIn('/api/fiscal/configuration', FISCAL_INTEGRATION_JS)
        self.assertIn('/api/fiscal/certificate', FISCAL_INTEGRATION_JS)
        self.assertIn('/api/fiscal/sefaz/status', FISCAL_INTEGRATION_JS)
        self.assertIn('/api/accounting/export?period=', FISCAL_INTEGRATION_JS)
        self.assertIn('A senha abre o PFX nesta operação e não é armazenada', FISCAL_INTEGRATION_JS)
        self.assertIn('Emissão e produção permanecem bloqueadas', FISCAL_INTEGRATION_JS)
        self.assertIn('CSV, XML e manifesto com SHA-256', FISCAL_INTEGRATION_JS)
        self.assertIn('@media (max-width: 620px)', FISCAL_INTEGRATION_CSS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', FISCAL_INTEGRATION_CSS)
        self.assertIn('min-height: 44px', FISCAL_INTEGRATION_CSS)
        self.assertIn('/theme/fiscal-integration.css?v=2.2.0-fiscal-readiness-44', INDEX)
        self.assertIn('/js/modules/fiscal-integration.js?v=2.2.0-fiscal-readiness-44', INDEX)
        self.assertIn('/js/modules/fiscal-integration.js?v=2.2.0-fiscal-readiness-44', SERVICE_WORKER)
        self.assertIn("sivs-v2.2.0-portal-agent-viewer-80", SERVICE_WORKER)

    def test_crm_exposes_the_signed_website_lead_inbox(self):
        self.assertIn('id="newLeadsView"', APP)
        self.assertIn('aria-pressed="false"', APP)
        self.assertIn('function toggleNewLeadsView()', APP)
        self.assertIn('F("telefone", "Telefone", "tel")', APP)
        self.assertIn('F("email", "E-mail", "email")', APP)
        self.assertIn('.toolbar-actions .secondary[aria-pressed="true"]', COMPONENTS)
        self.assertIn('/app.js?v=2.2.0-dashboard-tender-context-84', INDEX)
        self.assertIn('/app.js?v=2.2.0-dashboard-tender-context-84', SERVICE_WORKER)

    def test_tender_documents_use_vault_edital_checklist_and_guarded_packages(self):
        self.assertIn('/api/tender-documents', APP)
        self.assertIn('SIVSTenderDocuments?.settingsHTML', APP)
        self.assertIn('SIVSTenderDocuments?.detailHTML', APP)
        self.assertIn('id="tenderDocumentVault"', TENDER_DOCUMENTS_JS)
        self.assertIn('id="tenderParticipationForm"', TENDER_DOCUMENTS_JS)
        self.assertIn('item/página do edital'.lower(), TENDER_DOCUMENTS_JS.lower())
        self.assertIn('O edital é a fonte da verdade.', TENDER_DOCUMENTS_JS)
        self.assertIn('qualificationWithInitialProposal', TENDER_DOCUMENTS_JS)
        self.assertIn('selectedDocumentIds', TENDER_DOCUMENTS_JS)
        self.assertIn('id="addTenderCustomRequirement"', TENDER_DOCUMENTS_JS)
        self.assertIn('id="tenderCustomRequirementDialog"', TENDER_DOCUMENTS_JS)
        self.assertIn('data-document-choice', TENDER_DOCUMENTS_JS)
        self.assertIn('data-expires=', TENDER_DOCUMENTS_JS)
        self.assertIn('expiresAt.required = needsExpiry', TENDER_DOCUMENTS_JS)
        self.assertIn('Checklists confirmados que dependam dele voltarão para rascunho', TENDER_DOCUMENTS_JS)
        self.assertIn('Documento específico solicitado pelo edital', TENDER_DOCUMENTS_JS)
        self.assertIn('/participation-documents', TENDER_DOCUMENTS_JS)
        self.assertIn('/participation-package?stage=', TENDER_DOCUMENTS_JS)
        self.assertIn('credentials: "same-origin"', TENDER_DOCUMENTS_JS)
        self.assertIn('@media (max-width: 560px)', TENDER_DOCUMENTS_CSS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', TENDER_DOCUMENTS_CSS)
        self.assertIn('min-height: 44px', TENDER_DOCUMENTS_CSS)
        self.assertIn('.tender-document-choices', TENDER_DOCUMENTS_CSS)
        self.assertIn('.tender-custom-requirements', TENDER_DOCUMENTS_CSS)
        self.assertIn('/theme/tender-documents.css?v=2.2.0-tender-documents-52', INDEX)
        self.assertIn('/js/modules/tender-documents.js?v=2.2.0-tender-extraction-58', INDEX)
        self.assertIn('/theme/tender-documents.css?v=2.2.0-tender-documents-52', SERVICE_WORKER)
        self.assertIn('/js/modules/tender-documents.js?v=2.2.0-tender-extraction-58', SERVICE_WORKER)
        self.assertIn('if (!dialog.open) dialog.showModal();', APP)
        self.assertIn('data-notification-target', APP)

    def test_tender_proposal_is_versioned_priced_and_human_approved(self):
        self.assertIn('SIVSTenderProposal?.detailHTML', APP)
        self.assertIn('SIVSTenderProposal?.bindDetail', APP)
        self.assertIn('id="tenderCommercialProposal"', TENDER_PROPOSAL_JS)
        self.assertIn('id="tenderCommercialProposalForm"', TENDER_PROPOSAL_JS)
        self.assertIn('data-floor', TENDER_PROPOSAL_JS)
        self.assertIn('data-supply-mode', TENDER_PROPOSAL_JS)
        self.assertIn('catalogExceptionReason', TENDER_PROPOSAL_JS)
        self.assertIn('availableQuantity', TENDER_PROPOSAL_JS)
        self.assertIn('operationalLink', TENDER_PROPOSAL_JS)
        self.assertIn('Conectada à Licitação', TENDER_PROPOSAL_JS)
        self.assertIn('id="tenderOperationalHandoffForm"', TENDER_PROPOSAL_JS)
        self.assertIn('/operational-handoff', TENDER_PROPOSAL_JS)
        self.assertIn('Gerar fluxo operacional conectado', TENDER_PROPOSAL_JS)
        self.assertIn('.proposal-handoff-form', TENDER_PROPOSAL_CSS)
        self.assertIn('Solicitar aprovação independente', TENDER_PROPOSAL_JS)
        self.assertIn('Quem preparou ou enviou esta versão não pode aprová-la', TENDER_PROPOSAL_JS)
        self.assertIn('/commercial-proposal-package', TENDER_PROPOSAL_JS)
        self.assertIn('credentials: "same-origin"', TENDER_PROPOSAL_JS)
        self.assertIn('@media (max-width: 560px)', TENDER_PROPOSAL_CSS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', TENDER_PROPOSAL_CSS)
        self.assertIn('min-height: 44px', TENDER_PROPOSAL_CSS)
        self.assertIn('620ms', TENDER_PROPOSAL_CSS)
        self.assertIn('/theme/tender-proposal.css?v=2.2.0-tender-handoff-55', INDEX)
        self.assertIn('/js/modules/tender-proposal.js?v=2.2.0-tender-handoff-55', INDEX)
        self.assertIn('/theme/tender-proposal.css?v=2.2.0-tender-handoff-55', SERVICE_WORKER)
        self.assertIn('/js/modules/tender-proposal.js?v=2.2.0-tender-handoff-55', SERVICE_WORKER)

    def test_notification_center_supports_item_actions_history_and_preferences(self):
        for element_id in (
            "notificationDialog", "notificationActiveTab", "notificationHistoryTab",
            "notificationPreferencesDialog", "notificationPreferencesForm",
        ):
            self.assertIn(f'id="{element_id}"', INDEX)
        self.assertIn('data-notification-record', APP)
        self.assertIn('data-notification-dismiss', APP)
        self.assertIn('/api/notifications/${Number(id)}/${action}', APP)
        self.assertIn('/api/notification-preferences', APP)
        self.assertIn('notificationItemAction', APP)
        self.assertIn('notification_preferences', SERVER)
        self.assertIn('resolved_at', SERVER)
        self.assertIn('notification_email_deliveries', SERVER)
        self.assertIn('.notification-item-actions', COMPONENTS)

    def test_tender_autonomy_is_explicit_and_does_not_fake_portal_execution(self):
        self.assertIn('id="tenderAutonomyForm"', APP)
        self.assertIn('captureRegardlessOfValue', APP)
        self.assertIn('captureSingleCatalogItem', APP)
        self.assertIn('singleItemPolicy.disabled = true', APP)
        self.assertIn('catalog_priority', APP)
        self.assertIn('every_2_hours', APP)
        self.assertIn('autoFetchOfficialDetails', APP)
        self.assertIn('autoConvertCompatible', APP)
        self.assertIn('portalAgentEnabled', APP)
        self.assertIn('autoStartShadowRun', APP)
        self.assertIn('SIVSTenderPortalAgent?.detailHTML', APP)
        self.assertIn('/portal-agent/evaluate', TENDER_PORTAL_AGENT_JS)
        self.assertIn('idempotencyKey', TENDER_PORTAL_AGENT_JS)
        self.assertIn('A IA observa e sugere; o sistema valida piso', TENDER_PORTAL_AGENT_JS)
        self.assertIn('CAPTCHA, MFA', TENDER_PORTAL_AGENT_JS)
        self.assertIn('@media (max-width: 620px)', TENDER_PORTAL_AGENT_CSS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', TENDER_PORTAL_AGENT_CSS)
        self.assertIn('min-height: 44px', TENDER_PORTAL_AGENT_CSS)
        self.assertIn('/theme/tender-portal-agent.css?v=2.2.0-portal-agent-viewer-80', INDEX)
        self.assertIn('/js/modules/tender-portal-agent.js?v=2.2.0-portal-agent-viewer-80', INDEX)
        self.assertIn('/theme/tender-portal-agent.css?v=2.2.0-portal-agent-viewer-80', SERVICE_WORKER)
        self.assertIn('/js/modules/tender-portal-agent.js?v=2.2.0-portal-agent-viewer-80', SERVICE_WORKER)
        self.assertIn('data-portal-agent-viewer', TENDER_PORTAL_AGENT_JS)
        self.assertIn('portal-agent/viewer', TENDER_PORTAL_AGENT_JS)
        self.assertIn('referrerPolicy = "no-referrer"', TENDER_PORTAL_AGENT_JS)
        self.assertIn('.portal-agent-viewer-frame', TENDER_PORTAL_AGENT_CSS)
        self.assertIn('não contorna CAPTCHA', APP)
        self.assertIn('AGENTE_SHADOW_APOS_APROVACAO', SERVER)
        self.assertIn('/api/tenders/coverage', APP)
        self.assertIn('tenderCoverageHTML', APP)
        self.assertIn('CONTROLE DE COBERTURA', APP)
        self.assertIn('tender_retry_queue', SERVER)
        self.assertIn('TENDER_RETRY_MAX_ATTEMPTS = 5', SERVER)

    def test_tender_control_and_isolated_linux_worker_are_governed_and_accessible(self):
        self.assertIn('SIVSTenderControl?.detailHTML', APP)
        self.assertIn('SIVSTenderControl?.bindDetail', APP)
        self.assertIn('CONTROLE DA PARTICIPAÇÃO', TENDER_CONTROL_JS)
        self.assertIn('expectedRevision', TENDER_CONTROL_JS)
        self.assertIn('/control/evidence', TENDER_CONTROL_JS)
        self.assertIn('Probabilidade x impacto', TENDER_CONTROL_JS)
        self.assertIn('@media (max-width: 620px)', TENDER_CONTROL_CSS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', TENDER_CONTROL_CSS)
        self.assertIn('min-height: 44px', TENDER_CONTROL_CSS)
        self.assertIn('/theme/tender-control.css?v=2.2.0-tender-control-78', INDEX)
        self.assertIn('/js/modules/tender-control.js?v=2.2.0-tender-control-78', INDEX)
        self.assertIn('/theme/tender-control.css?v=2.2.0-tender-control-78', SERVICE_WORKER)
        self.assertIn('/js/modules/tender-control.js?v=2.2.0-tender-control-78', SERVICE_WORKER)
        self.assertIn('sivs-v2.2.0-portal-agent-viewer-80', SERVICE_WORKER)
        self.assertIn('tender_control_profiles', SERVER)
        self.assertIn('tender_protocol_evidence', SERVER)
        self.assertIn('comprovante de protocolo e imutavel', SERVER)
        self.assertIn('--remote-webdriver-url', TENDER_AGENT_WORKER)
        self.assertIn('--loop', TENDER_AGENT_WORKER)
        self.assertIn('exclusive_profile', TENDER_AGENT_WORKER)
        self.assertIn('selenium/standalone-chrome:4.47.0-20260808', TENDER_AGENT_COMPOSE)
        self.assertIn('shm_size: 2gb', TENDER_AGENT_COMPOSE)
        self.assertIn('127.0.0.1:${SIVS_TENDER_AGENT_NOVNC_PORT:-7900}:7900', TENDER_AGENT_COMPOSE)
        self.assertNotIn('4444:4444', TENDER_AGENT_COMPOSE)
        self.assertNotIn('--allow-external-effects', TENDER_AGENT_COMPOSE)
        self.assertIn('no-new-privileges:true', TENDER_AGENT_COMPOSE)
        self.assertIn('viewer-snapshots', TENDER_AGENT_COMPOSE)
        self.assertIn('viewer-proxy', TENDER_AGENT_COMPOSE)
        self.assertIn('SIVS_TENDER_AGENT_VIEWER_SECRET', TENDER_AGENT_COMPOSE)
        self.assertIn('WebDriver, teclado, mouse ou execucao de comandos', (ROOT.parent / "tools" / "tender-agent" / "viewer.py").read_text(encoding="utf-8"))

    def test_tender_extraction_ocr_and_exception_center_are_connected(self):
        self.assertIn('tenderExtractionHTML', APP)
        self.assertIn('tenderExceptionCenterHTML', APP)
        self.assertIn('/api/tenders/exceptions', APP)
        self.assertIn('/extract', APP)
        self.assertIn('data-resolve-tender-exception', APP)
        self.assertIn('sugerido pela extração; confirme no edital', TENDER_DOCUMENTS_JS)
        self.assertIn('tender_analysis_exceptions', SERVER)
        self.assertIn('document_extraction_blocked', SERVER)
        self.assertIn('TENDER_OCR_MAX_PAGES = 40', SERVER)
        self.assertIn('tesseract-ocr-por', DOCKERFILE)
        self.assertIn('.deterministic-extraction', TENDERS_CSS)
        self.assertIn('.tender-exception-list button:focus-visible', TENDERS_CSS)
        self.assertIn('@media (max-width: 760px)', TENDERS_CSS)

    def test_company_permissions_are_granular_accessible_and_responsive(self):
        for element_id in (
            "permissionsDialog", "permissionsForm", "permissionsSearch",
            "permissionsModuleList", "permissionsError", "permissionsApplyRole",
            "permissionsSelectionSummary", "permissionsSubmit",
        ):
            self.assertIn(f'id="{element_id}"', INDEX)
        self.assertIn("effective_permissions", APP)
        self.assertIn("effectivePermissions", APP)
        self.assertIn("effectiveCapabilities", APP)
        self.assertIn("effectiveActions", APP)
        self.assertIn("data-permission-action", APP)
        self.assertIn("data-permission-functional-action", APP)
        self.assertIn("data-permission-category-mode", APP)
        self.assertIn("state.pendingUser", APP)
        self.assertIn('canAction(module, "create")', APP)
        self.assertIn("data-permission-capability", INDEX)
        self.assertIn('id="permissionsError" class="form-error hidden" role="alert"', INDEX)
        self.assertIn("@media (max-width: 700px)", PERMISSIONS_CSS)
        self.assertIn("@media (prefers-reduced-motion: reduce)", PERMISSIONS_CSS)
        self.assertIn("min-height: 44px", PERMISSIONS_CSS)
        self.assertIn("position: fixed", PERMISSIONS_CSS)
        self.assertIn(".dialog.permissions-dialog[open]", MOTION)
        self.assertIn("background: var(--color-surface, #fff)", PERMISSIONS_CSS)
        self.assertIn("/theme/permissions.css?v=2.2.0-functional-control-43", INDEX)
        self.assertIn("/theme/permissions.css?v=2.2.0-functional-control-43", SERVICE_WORKER)

    def test_controllership_is_integrated_responsive_and_never_uses_placeholder_values(self):
        self.assertIn('["controladoria", "Visão financeira"]', APP)
        self.assertIn('if (screen === "controladoria") return await loadManagementOverview()', APP)
        self.assertIn('/api/management/overview', MANAGEMENT_JS)
        self.assertIn('data-management-go="contas_receber"', MANAGEMENT_JS)
        self.assertIn('data-management-go="estoque"', MANAGEMENT_JS)
        self.assertIn('Acesso restrito', MANAGEMENT_JS)
        self.assertIn('não substitui DRE contábil', MANAGEMENT_JS)
        self.assertNotIn('Math.random', MANAGEMENT_JS)
        self.assertIn('@media (max-width: 620px)', MANAGEMENT_CSS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', MANAGEMENT_CSS)
        self.assertIn('min-height: 48px', MANAGEMENT_CSS)
        self.assertIn('/theme/management-control.css?v=2.2.0-functional-control-43', INDEX)
        self.assertIn('/js/modules/management-control.js?v=2.2.0-functional-control-43', INDEX)
        self.assertIn('/js/modules/management-control.js?v=2.2.0-functional-control-43', SERVICE_WORKER)

    def test_financial_settlement_fields_explain_the_connected_cash_flow(self):
        self.assertIn('F("data_pagamento", "Data do pagamento", "date")', APP)
        self.assertIn('F("data_recebimento", "Data do recebimento", "date")', APP)
        self.assertIn('F("conta", "Conta de saída")', APP)
        self.assertIn('F("conta", "Conta de entrada")', APP)
        self.assertIn('Ao marcar como paga, o sistema gera uma saída de caixa rastreável.', APP)
        self.assertIn('Ao marcar como recebido, o sistema gera uma entrada de caixa rastreável.', APP)
        self.assertIn('"Em aberto": ["Pago", "Vencido", "Cancelado"]', APP)
        self.assertIn('"Em aberto": ["Recebido", "Vencido", "Cancelado"]', APP)
        self.assertIn('/app.js?v=2.2.0-dashboard-tender-context-84', INDEX)
        self.assertIn('/app.js?v=2.2.0-dashboard-tender-context-84', SERVICE_WORKER)

    def test_whatsapp_workspace_is_crm_linked_permissioned_and_accessible(self):
        whatsapp_js = (ROOT / "static" / "js" / "modules" / "whatsapp.js").read_text(encoding="utf-8")
        whatsapp_css = (ROOT / "static" / "theme" / "whatsapp.css").read_text(encoding="utf-8")
        connection_css = (ROOT / "static" / "theme" / "whatsapp-connection.css").read_text(encoding="utf-8")
        self.assertIn('["whatsapp", "Atendimento WhatsApp"]', APP)
        self.assertIn('if (screen === "whatsapp") return await loadWhatsApp()', APP)
        self.assertIn('/js/modules/whatsapp.js?v=2.2.0-uazapi-whatsapp-64', INDEX)
        self.assertIn('/theme/whatsapp.css?v=2.2.0-uazapi-whatsapp-64', INDEX)
        self.assertIn('/theme/whatsapp-connection.css?v=2.2.0-uazapi-whatsapp-64', INDEX)
        self.assertIn('CAIXA DE ENTRADA COMPARTILHADA', whatsapp_js)
        self.assertIn('MANUAL_COMPLIANCE_REQUIRED', SERVER)
        self.assertIn('reply_whatsapp', SERVER)
        self.assertIn('view_all_whatsapp', SERVER)
        self.assertIn('/api/whatsapp/instance/connect', whatsapp_js)
        self.assertIn('/api/whatsapp/instance/status', whatsapp_js)
        self.assertIn('não é a Cloud API oficial da Meta', whatsapp_js)
        self.assertIn('customer_window_expires_at', SERVER)
        self.assertIn('prefers-reduced-motion:reduce', whatsapp_css)
        self.assertIn('@media(max-width:390px)', whatsapp_css)
        self.assertIn('min-height:44px', whatsapp_css)
        self.assertIn('@media (prefers-reduced-motion: reduce)', connection_css)
        self.assertIn('min-height: 44px', connection_css)

    def test_control_center_is_admin_only_observable_and_accessible(self):
        self.assertIn('["control_center", "Operação e segurança"]', APP)
        self.assertIn('state.capabilities.control_center', APP)
        self.assertIn('{ "/controle": "control_center" }', APP)
        self.assertIn('/api/control-center', CONTROL_CENTER_JS)
        self.assertIn('/api/telemetry/client-error', CONTROL_CENTER_JS)
        self.assertIn('data-end-session', CONTROL_CENTER_JS)
        self.assertIn('class="control-people"', CONTROL_CENTER_JS)
        self.assertIn('Cada pessoa aparece uma vez', CONTROL_CENTER_JS)
        self.assertIn('id="controlEventFilter"', CONTROL_CENTER_JS)
        self.assertIn('id="controlChangeSearch"', CONTROL_CENTER_JS)
        self.assertIn('data-resolve-event', CONTROL_CENTER_JS)
        self.assertIn('operationsRows', CONTROL_CENTER_JS)
        self.assertIn('teamRows', CONTROL_CENTER_JS)
        self.assertIn('data-control-record', CONTROL_CENTER_JS)
        self.assertIn('id="openUsersSettings"', CONTROL_CENTER_JS)
        self.assertIn('.control-work-item', CONTROL_CENTER_CSS)
        self.assertIn('.control-team-member', CONTROL_CENTER_CSS)
        self.assertIn('openRecord: openRecordById', APP)
        self.assertIn('aria-label="Resumo operacional"', CONTROL_CENTER_JS)
        self.assertIn('@media (prefers-reduced-motion: reduce)', CONTROL_CENTER_CSS)
        self.assertIn('/theme/control-center.css?v=2.2.0-admin-operations-79', INDEX)
        self.assertIn('/js/modules/control-center.js?v=2.2.0-admin-operations-79', INDEX)
        self.assertIn('/js/modules/control-center.js?v=2.2.0-admin-operations-79', SERVICE_WORKER)

    def test_every_schema_has_a_specialized_registration_profile(self):
        schema_block = APP.split("const schemas = {", 1)[1].split("\n};\n\nconst formDomains", 1)[0]
        profile_block = APP.split("const registrationProfiles = {", 1)[1].split(
            "\n};\n\nfunction getRecordProfile", 1
        )[0]
        schemas = set(re.findall(r"^  ([a-z_]+): \[", schema_block, re.MULTILINE))
        profiles = set(re.findall(r"^  ([a-z_]+): P\(", profile_block, re.MULTILINE))
        self.assertEqual(46, len(schemas))
        self.assertEqual(schemas, profiles)

    def test_specialized_form_keeps_subject_and_governance_contract(self):
        required_ids = {
            "recordProfileHero", "recordProgressValue", "recordIdentification",
            "recordSpecifics", "recordRelationships", "recordGovernance",
            "dynamicFields", "relationshipList", "recordResources",
        }
        ids = set(re.findall(r'id="([A-Za-z][A-Za-z0-9_-]+)"', INDEX))
        self.assertTrue(required_ids.issubset(ids))
        self.assertIn('name="assunto" required', INDEX)
        self.assertIn("function validateSpecializedRecord", APP)
        self.assertIn("function updateRecordCompleteness", APP)
        self.assertIn('submitButton.setAttribute("aria-busy", "true")', APP)
        self.assertIn('id="formError" class="form-error hidden" role="alert"', INDEX)
        self.assertIn("function loadingStateHTML", APP)
        self.assertIn(".loading-state", COMPONENTS)

    def test_new_record_uses_the_hidden_id_control_not_the_form_id_property(self):
        self.assertIn("form.elements.id.value", APP)
        self.assertNotIn("form.id.value", APP)
        self.assertIn('id="newButton" class="primary" type="button"', INDEX)
        self.assertIn("self.skipWaiting()", SERVICE_WORKER)
        self.assertIn("self.clients.claim()", SERVICE_WORKER)

    def test_new_records_use_valid_initial_status_and_approval_actions_are_authorized(self):
        self.assertIn('updateStatusOptions(module, item?.status || "")', APP)
        self.assertIn('const effectiveStatus = selected || options[0]', APP)
        self.assertIn('const moduleStatusTransitions = {', APP)
        self.assertIn('transitions[selected]', APP)
        self.assertIn('function canDecideApproval(approval)', APP)
        self.assertIn('canDecideApproval(item)', APP)
        self.assertIn('$("#newButton").classList.add("hidden")', APP)
        self.assertIn('F("catalogo_seccol", "Exibir no portfólio", "checkbox")', APP)
        self.assertIn("min-height:44px", PRODUCTIVITY)

    def test_static_html_has_no_duplicate_ids(self):
        ids = re.findall(r'id="([A-Za-z][A-Za-z0-9_-]+)"', INDEX)
        self.assertEqual(len(ids), len(set(ids)))

    def test_theme_and_experience_layers_are_loaded_in_order(self):
        assets = [
            "/theme/tokens.css", "/styles.css", "/theme/foundations.css",
            "/theme/responsive.css", "/theme/components.css", "/theme/productivity.css", "/theme/motion.css",
            "/js/core/platform.js", "/js/core/state.js", "/js/core/formatters.js", "/js/core/http.js",
            "/js/core/preferences.js", "/js/core/drafts.js", "/js/ui/motion.js",
            "/js/ui/dialogs.js", "/js/ui/pointer.js", "/js/ui/navigation.js",
            "/js/ui/command-palette.js", "/js/ui/record-disclosure.js", "/js/ui/experience.js", "/app.js",
        ]
        positions = [INDEX.index(asset) for asset in assets]
        self.assertEqual(positions, sorted(positions))
        for asset in assets:
            self.assertIn(asset, SERVICE_WORKER)
        self.assertIn("--color-seccol", TOKENS)
        self.assertIn(".data-table td { font-size: var(--text-sm)", COMPONENTS)
        self.assertIn(".record-form-guide nav button > span { font-size: var(--text-xs); }", COMPONENTS)
        self.assertIn(":focus-visible", FOUNDATIONS)
        self.assertIn("prefers-reduced-motion: reduce", MOTION)
        self.assertNotIn("--motion-duration-", MOTION)
        self.assertNotIn("--motion-ease-", MOTION)
        theme = "\n".join((
            TOKENS, FOUNDATIONS, RESPONSIVE, COMPONENTS, CONTROL_CENTER_CSS,
            WORKFLOW_ITEMS_CSS, PERMISSIONS_CSS, PRODUCTIVITY, MOTION,
            TENDER_PROPOSAL_CSS,
        ))
        defined_tokens = set(re.findall(r"(--[a-z0-9-]+)\s*:", theme))
        used_tokens = set(re.findall(r"var\((--[a-z0-9-]+)", theme))
        self.assertFalse(used_tokens - defined_tokens)

    def test_navigation_and_motion_keep_accessibility_contract(self):
        self.assertIn('class="skip-link"', INDEX)
        self.assertIn('id="pageStatus"', INDEX)
        self.assertIn('id="sidebarScrim"', INDEX)
        self.assertIn('aria-controls="sidebar"', INDEX)
        self.assertIn("transitionOut", MOTION_JS)
        self.assertIn("transitionIn", MOTION_JS)
        self.assertIn("closeDialog", DIALOGS_JS)
        self.assertIn("setNavigation", NAVIGATION_JS)
        self.assertIn("compactNavigation", NAVIGATION_JS)
        self.assertIn("sidebar.inert", NAVIGATION_JS)
        self.assertIn("collapsedNavGroups()", PREFERENCES_JS)
        self.assertIn("setNavGroupCollapsed", PREFERENCES_JS)
        self.assertIn("data-nav-group-toggle", APP)
        self.assertIn("revealNavigationGroup(screen)", APP)
        self.assertIn("aria-controls=\"nav-group-links-", APP)
        self.assertIn(".nav-group-toggle", COMPONENTS)
        self.assertIn("@media (max-width: 900px)", RESPONSIVE)
        self.assertIn("min-height: 44px", RESPONSIVE)
        self.assertIn(".source-open", RESPONSIVE)
        self.assertIn(".portfolio-card footer a", RESPONSIVE)
        self.assertIn("@media (max-width: 900px) { .command-trigger { min-height: 44px; } }", PRODUCTIVITY)
        self.assertIn("100dvh", RESPONSIVE)
        self.assertIn("MutationObserver", EXPERIENCE)
        self.assertIn("await ui.transitionOut?.(content)", APP)
        self.assertIn('document.body.classList.add("is-authenticated")', APP)
        self.assertIn("body:not(.is-authenticated) .skip-link", FOUNDATIONS)

    def test_core_state_formatters_and_http_are_extracted(self):
        self.assertIn("global.SIVSState", STATE_JS)
        self.assertIn("core.escapeHTML", FORMATTERS_JS)
        self.assertIn("core.safeExternalURL", FORMATTERS_JS)
        self.assertIn("core.documentBR", FORMATTERS_JS)
        self.assertIn('documentField.inputMode = "numeric"', APP)
        self.assertIn('documentField.maxLength = 18', APP)
        self.assertIn('payload.documento = String(payload.documento || "").replace(/\\D/g, "")', APP)
        self.assertIn("core.createApiClient", HTTP_JS)
        self.assertIn("X-CSRF-Token", HTTP_JS)
        self.assertIn("const state = window.SIVSState", APP)
        self.assertIn("window.SIVSCore.createApiClient", APP)
        self.assertIn("moduleRequest: null", STATE_JS)
        self.assertIn("state.moduleRequest?.abort()", APP)
        self.assertIn("failure.name === \"AbortError\"", APP)

    def test_party_document_is_checked_before_the_form_is_unlocked(self):
        self.assertIn('id="partyDocumentLookup"', INDEX)
        self.assertIn("function lookupExistingParty", APP)
        self.assertIn("/api/partners/lookup?", APP)
        self.assertIn("Abrir cadastro existente", APP)
        self.assertIn("Documento disponível para novo cadastro", APP)
        self.assertIn("partyDocumentLookupState.status", APP)
        self.assertIn(".party-document-lookup", COMPONENTS)
        self.assertIn('/theme/components.css?v=2.2.0-notification-center-77', INDEX)
        self.assertIn('/theme/components.css?v=2.2.0-notification-center-77', SERVICE_WORKER)

    def test_assistant_is_contextual_accessible_and_resilient(self):
        self.assertIn('id="assistantRailButton"', INDEX)
        self.assertIn('id="assistantScrim"', INDEX)
        self.assertIn('id="assistantReset"', INDEX)
        self.assertIn('id="assistantContextLabel"', INDEX)
        self.assertNotIn('id="assistantModeBadge"', INDEX)
        self.assertNotIn("Modo seguro", INDEX)
        self.assertNotIn("IA ativa", INDEX)
        self.assertIn('role="dialog"', INDEX)
        self.assertIn('aria-modal="true"', INDEX)
        self.assertIn("function assistantContextSnapshot", APP)
        self.assertIn("conversation_id: assistantConversationId", APP)
        self.assertNotIn("history: priorHistory", APP)
        self.assertIn("function assistantSourceElement", APP)
        self.assertIn("openAssistantSource", APP)
        self.assertIn("requestSubmit()", APP)
        self.assertIn('event.key !== "Tab"', APP)
        self.assertIn("/api/assistant/capabilities", APP)
        self.assertIn("ASSISTANT_KNOWLEDGE_BASE", SERVER)
        self.assertIn("assistant_access_policy", SERVER)
        self.assertIn("source_ids", SERVER)
        self.assertIn("assistant_conversations", SERVER)
        self.assertIn('"data_collection": "deny", "zdr": True', SERVER)
        self.assertIn('f"assistant:{session[\'company_id\']}:{session[\'id\']}"', SERVER)
        self.assertIn(".assistant-rail-trigger", PRODUCTIVITY)
        self.assertIn(".assistant-message-sources", PRODUCTIVITY)
        self.assertIn("@media(prefers-reduced-motion:reduce)", PRODUCTIVITY)
        self.assertIn('/theme/productivity.css?v=2.2.0-dashboard-clarity-82', INDEX)
        self.assertIn('/theme/productivity.css?v=2.2.0-dashboard-clarity-82', SERVICE_WORKER)
        self.assertIn('/app.js?v=2.2.0-dashboard-tender-context-84', INDEX)
        self.assertIn('/app.js?v=2.2.0-dashboard-tender-context-84', SERVICE_WORKER)

    def test_productivity_layer_keeps_familiar_navigation_and_adds_real_tools(self):
        self.assertIn('id="commandButton"', INDEX)
        self.assertIn('id="commandDialog"', INDEX)
        self.assertIn('id="draftNotice"', INDEX)
        self.assertNotIn('id="globalSearch"', INDEX)
        self.assertIn("global.SIVSPreferences", PREFERENCES_JS)
        self.assertIn("global.SIVSDrafts", DRAFTS_JS)
        self.assertIn("sessionStorage", DRAFTS_JS)
        self.assertIn("Ctrl", INDEX)
        self.assertIn("commandPalette", COMMAND_JS)
        self.assertIn("/api/search", APP)
        self.assertIn("workCenterHTML", APP)
        self.assertIn("saveRecordDraftNow", APP)
        self.assertIn("prefers-reduced-motion: reduce", PRODUCTIVITY)

    def test_operational_forms_share_master_records_by_validated_id(self):
        self.assertIn("const recordReferenceRules", APP)
        self.assertIn("data-record-reference", APP)
        self.assertIn("function populateRecordReferenceFields", APP)
        self.assertIn('/api/partners/options', APP)
        self.assertIn('state.partyOptions', APP)
        self.assertIn('payload[`${field.key}_id`]', APP)
        self.assertIn(".record-reference-field", COMPONENTS)
        self.assertIn("RECORD_REFERENCE_RULES", (ROOT / "server.py").read_text(encoding="utf-8"))

    def test_modern_components_and_progressive_record_keep_accessible_fallbacks(self):
        self.assertIn('id="recordDisclosure"', INDEX)
        self.assertIn('id="recordOptionalToggle"', INDEX)
        self.assertIn("recordDisclosure", RECORD_DISCLOSURE_JS)
        self.assertIn("ensureVisible", RECORD_DISCLOSURE_JS)
        self.assertIn("is-essential-mode", RECORD_DISCLOSURE_JS)
        self.assertIn("record-optional", APP)
        self.assertIn("::-webkit-scrollbar-thumb", COMPONENTS)
        self.assertIn("scrollbar-width: thin", COMPONENTS)
        self.assertIn("appearance: base-select", COMPONENTS)
        self.assertIn("@supports (appearance: base-select)", COMPONENTS)
        self.assertNotIn("Ã", RECORD_DISCLOSURE_JS)

    def test_registration_forms_use_the_right_drawer_and_party_defaults(self):
        self.assertIn("inset: 0 0 0 258px", COMPONENTS)
        self.assertIn(".form-drawer", COMPONENTS)
        self.assertIn("sivs-drawer-in", MOTION)
        for dialog_id in ("userDialog", "settingsDialog", "companyDialog", "passwordDialog"):
            self.assertRegex(INDEX, rf'id="{dialog_id}" class="[^"]*form-drawer')
        self.assertIn('roleField.value = "Cliente (C)"', APP)
        self.assertIn('roleField.value = "Fornecedor (F)"', APP)
        self.assertIn("function applyPartyFieldContext", APP)
        self.assertIn('"Nome completo"', APP)
        self.assertIn('"Qualificação do fornecedor"', APP)
        self.assertIn(".party-context-hidden", COMPONENTS)

    def test_mobile_install_experience_has_manifest_icons_and_ios_fallback(self):
        self.assertIn('data-install-app', INDEX)
        self.assertIn('id="installDialog"', INDEX)
        self.assertIn("/js/ui/install-app.js", INDEX)
        self.assertIn("beforeinstallprompt", INSTALL_APP_JS)
        self.assertIn("Adicionar à Tela de Início", INSTALL_APP_JS)
        self.assertIn("(display-mode: standalone)", INSTALL_APP_JS)
        self.assertIn('"sizes": "192x192"', MANIFEST)
        self.assertIn('"sizes": "512x512"', MANIFEST)
        self.assertIn('"display": "standalone"', MANIFEST)
        self.assertIn("/assets/brand/seccol-app-192.png", SERVICE_WORKER)
        self.assertIn("/assets/brand/seccol-app-512.png", SERVICE_WORKER)
        self.assertIn("/api/partner-lookup?cnpj=", APP)
        self.assertIn("/api/partner-lookup?cep=", APP)
        self.assertIn("function maskPartyCepField", APP)
        self.assertIn("autocomplete = \"postal-code\"", APP)
        self.assertIn("function dashboardGreeting", APP)

    def test_dashboard_priorities_explain_the_required_action(self):
        self.assertIn("O que fazer agora", APP)
        self.assertIn("item.requiredAction", APP)
        self.assertIn("Pendência identificada:", APP)
        self.assertIn("Veja qual pendência foi identificada", APP)
        self.assertIn("data-work-tender", APP)
        self.assertIn("showTenderDetail(tenderResultId)", APP)
        self.assertIn(".work-required-action", PRODUCTIVITY)
        self.assertIn(".work-pending-reason", PRODUCTIVITY)
        self.assertIn(".work-timing", PRODUCTIVITY)

    def test_initial_access_offers_login_without_reopening_completed_setup(self):
        self.assertIn('id="authModeSwitch"', INDEX)
        self.assertIn('id="authModeToggle"', INDEX)
        self.assertIn("authSetupAvailable", STATE_JS)
        self.assertIn('setup && state.authSetupAvailable', APP)
        self.assertIn('failure.code === "already_configured"', APP)
        self.assertIn('$("#authModeToggle").onclick', APP)
        self.assertIn("Já possui um acesso?", APP)

    def test_login_exposes_accessible_self_service_password_recovery(self):
        for element_id in (
            "forgotPasswordButton", "passwordRecoveryDialog",
            "passwordRecoveryRequestForm", "passwordRecoveryResetForm",
            "passwordRecoveryRequestStatus", "passwordRecoveryResetError",
        ):
            self.assertIn(f'id="{element_id}"', INDEX)
        self.assertIn('aria-labelledby="passwordRecoveryTitle"', INDEX)
        self.assertIn('autocomplete="new-password"', INDEX)
        self.assertIn('/api/password/forgot', APP)
        self.assertIn('/api/password/reset', APP)
        self.assertIn('new URLSearchParams(window.location.search)', APP)
        self.assertIn('.auth-recovery-link', COMPONENTS)

    def test_trash_has_recovery_and_confirmed_permanent_deletion(self):
        for dialog_id in (
            "trashPurgeDialog", "trashPurgeForm", "trashPurgeTitle",
            "trashPurgeConfirmationLabel", "trashPurgeError", "trashPurgeSubmit",
        ):
            self.assertIn(f'id="{dialog_id}"', INDEX)
        self.assertIn('data-trash-purge=', APP)
        self.assertIn('id="emptyTrash"', APP)
        self.assertIn('const expected = bulk ? "ESVAZIAR" : "EXCLUIR"', APP)
        self.assertIn('`/api/trash/${recordId}`', APP)
        self.assertIn('method: "DELETE"', APP)
        self.assertIn(".trash-actions", COMPONENTS)

    def test_sidebar_displays_local_date_with_weekday_and_daily_refresh(self):
        self.assertIn('id="systemDate"', INDEX)
        self.assertIn('id="globalDateDay"', INDEX)
        self.assertIn('class="global-date"', INDEX)
        self.assertIn('/js/ui/system-date.js', INDEX)
        self.assertIn('weekday: "long"', SYSTEM_DATE_JS)
        self.assertIn('month: "long"', SYSTEM_DATE_JS)
        self.assertIn('scheduleNextDay', SYSTEM_DATE_JS)
        self.assertIn('/js/ui/system-date.js', SERVICE_WORKER)

    def test_financial_expenses_use_admin_categories_and_inline_evidence(self):
        for element_id in (
            "financialDocumentSection", "financialDocumentTitle",
            "financialDocumentFile", "financialDocumentFileName",
        ):
            self.assertIn(f'id="{element_id}"', INDEX)
        self.assertIn('"financial-category"', APP)
        self.assertIn("payload.categoria_id", APP)
        self.assertIn('/api/financial/categories', APP)
        self.assertIn('id="financialCategoryForm"', APP)
        self.assertIn("Nota fiscal / comprovante de despesa", APP)
        self.assertIn("body.attachment", APP)
        self.assertIn(".financial-document-section", COMPONENTS)
        self.assertIn(".financial-category-row", COMPONENTS)
        self.assertIn("VALUES(243,'financial-categories-and-inline-evidence'", SERVER)


if __name__ == "__main__":
    unittest.main()
